//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CMessageDB, CMessageWrap, ImageInfo, NSData, NSString, UIImage;

@protocol IMsgExtendOperation <NSObject>
@property(nonatomic) CMessageWrap *m_refMessageWrap;
- (id)copy;

@optional
- (NSString *)GetDisplaySessionContent;
- (NSString *)GetDisplayContent;
- (void)UpdateMassSendContent:(NSString *)arg1;
- (BOOL)genImageFromMMAssetAndNotify:(id <MessageWrapImgDelegate>)arg1;
- (BOOL)IsHDImg;
- (void)setImage:(UIImage *)arg1 withImageInfo:(ImageInfo *)arg2 isLongOriginImage:(BOOL)arg3;
- (void)setImage:(UIImage *)arg1 withData:(NSData *)arg2 withImageInfo:(ImageInfo *)arg3 isLongOriginImage:(BOOL)arg4;
- (void)setImage:(UIImage *)arg1 withData:(NSData *)arg2 isLongOriginImage:(BOOL)arg3;
- (void)setImage:(UIImage *)arg1 isLongOriginImage:(BOOL)arg2;
- (void)SetOriginal:(BOOL)arg1;
- (unsigned long)GetContentAttributeBitSetFlag;
- (BOOL)GetDownloadThumbStatus:(unsigned int *)arg1;
- (BOOL)isShowAppMessageBlockButton;
- (BOOL)isShowAppBottomButton;
- (unsigned long)GetPreviewType;
- (NSString *)getFileExt;
- (void)UpdateVideoStatus:(CMessageDB *)arg1;
- (void)SetPlaySounded:(BOOL)arg1;
- (BOOL)IsPlaySounded;
- (BOOL)IsRecording;
- (void)SetPlayed;
- (BOOL)IsDownloadEnded;
- (BOOL)IsUnPlayed;
- (BOOL)SaveMesVoice:(NSString *)arg1;
- (NSString *)GetDownloadThumbPath;
- (NSString *)GetThumbPath;
- (void)ChangeForBackup;
- (void)UpdateGameInfo:(NSString *)arg1;
- (NSString *)GetGameStatReportString;
- (NSString *)GetContent;
- (void)UpdateContent:(NSString *)arg1;
- (void)ChangeForDisplayAnyhow;
- (void)ChangeForDisplay;
@end

